## @param architecture MongoDB&reg; architecture (`standalone` or `replicaset`)
##
architecture: replicaset
## @param useStatefulSet Set to true to use a StatefulSet instead of a Deployment (only when `architecture=standalone`)
##
useStatefulSet: true
## @param replicaCount Number of MongoDB&reg; nodes (only when `architecture=replicaset`)
## Ignored when mongodb.architecture=standalone
##
replicaCount: 2